### ISSUE TITLE
Create WebSocket Component

### ISSUE THREAD

**Issue by pedrouid** [WalletConnect/swift-walletconnect-lib#2]
The WebSocket component should establish a connection with the provided bridge server url through a secured websocket (wss) and handle its connection state ([check L975](https://github.com/WalletConnect/walletconnect-monorepo/blob/00c008891c20b21c7d233cf2ab4d2b5b96990a49/packages/core/src/index.ts#L975))

Whenever the connection state is disconnected or pending, the handler should queue any socket messages and dispatch them whenever the connection is reestablished ([check L1024](https://github.com/WalletConnect/walletconnect-monorepo/blob/00c008891c20b21c7d233cf2ab4d2b5b96990a49/packages/core/src/index.ts#L1024))

The WebSocket handler should also be able to encrypt and decrypt messages before passing it to other components whenever receiving any payloads ([check L1034](https://github.com/WalletConnect/walletconnect-monorepo/blob/00c008891c20b21c7d233cf2ab4d2b5b96990a49/packages/core/src/index.ts#L1034))

**Comment by hewigovens** [comment]
Looks like we can close this issue now

**Comment by pedrouid** [comment]
👍
